name: Deploy Blog to GitHub Pages

on:
  push:
    branches:
      - main 
  workflow_dispatch:   # Change if your default branch is different (e.g., master)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./   # Path to your project folder (adjust if needed)

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
